# Continuous Integration (CI) is the practice, in software
# engineering, of merging all developer working copies with a shared mainline
# several times a day < http://docs.platformio.org/page/ci/index.html >
#
# Documentation:
#
# * Travis CI Embedded Builds with PlatformIO
#   < https://docs.travis-ci.com/user/integration/platformio/ >
#
# * PlatformIO integration with Travis CI
#   < http://docs.platformio.org/page/ci/travis.html >
#
# * User Guide for `platformio ci` command
#   < http://docs.platformio.org/page/userguide/cmd_ci.html >
#
language: python
python:
    - "2.7"

env:
    - PLATFORMIO_CI_SRC=examples/advancedsettings/
    - PLATFORMIO_CI_SRC=examples/bme280test/

install:
    - git rm library.json
    - pip install -U platformio
    - pio upgrade
    - pio update
    - pio lib -g install 31  # Adafruit Unified Sensor
    - pio lib -g update

script:
# Build AVR Boards
- platformio ci --lib="." --board=uno --board=feather32u4 --board=megaatmega2560 --board=mayfly --board=gemma --board=metro

# Build SAMD Boards
- platformio ci --lib="." --board=adafruit_feather_m0

# Build ESP Boards
- platformio ci --lib="." --board=huzzah --board=featheresp32
